#!/usr/bin/env node

/**
 * cold-start/scripts/init-mb.js
 *
 * A small helper to initialize the Memory Bank skeleton in the current directory.
 *
 * - Creates .memory-bank/ (durable knowledge base)
 * - Creates .tasks/ (operational runtime memory)
 * - Creates .protocols/ (file-based protocols)
 * - Creates AGENTS.md + CLAUDE.md symlink/copy
 *
 * Safe by default: does NOT overwrite existing files.
 *
 * Update mode:
 * - --sync / --force: update explicitly framework-owned Memory Bank assets,
 *   runtime scripts, and recognized generated AGENTS.md; keep project/mixed
 *   files unchanged.
 */

const fs = require('fs');
const path = require('path');

const ROOT = process.cwd();
const MB = '.memory-bank';
const MEMORY_BANK_EXISTED_AT_START = fs.existsSync(path.join(ROOT, MB));
const TESTING_INDEX_EXISTED_AT_START = fs.existsSync(path.join(ROOT, MB, 'testing', 'index.md'));
const TESTING_STRATEGY_EXISTED_AT_START = fs.existsSync(path.join(ROOT, MB, 'testing', 'strategy.md'));
const TESTING_STRATEGY_ROUTER_ENTRY = !MEMORY_BANK_EXISTED_AT_START || TESTING_STRATEGY_EXISTED_AT_START
  ? '- [Testing strategy](strategy.md): минимальные глобальные правила тестирования и verification evidence.'
  : '';
const TESTING_SPEC_REGISTRY_ROW = !MEMORY_BANK_EXISTED_AT_START || TESTING_STRATEGY_EXISTED_AT_START
  ? '| testing | [.memory-bank/testing/strategy.md](testing/strategy.md) | active | Framework baseline testing policy. | explicit project-level user decision |'
  : TESTING_INDEX_EXISTED_AT_START
    ? '| testing | [.memory-bank/testing/index.md](testing/index.md) | active | Existing project testing policy. | explicit project-level user decision |'
    : '';
const SHARED_DIR = path.resolve(__dirname, '..');
const REFERENCES_DIR = path.join(SHARED_DIR, 'references');
const WORKFLOW_REFERENCES_DIR = path.join(REFERENCES_DIR, 'workflows');
const ROLE_REFERENCES_DIR = path.join(REFERENCES_DIR, 'roles');
const AGENTS_TEMPLATE_CATEGORY = 'deployable';
const AGENTS_TEMPLATE_FILE = 'AGENTS.md';
const CONSTITUTION_TEMPLATE_FILE = 'constitution-template.md';
const RUNTIME_SCRIPT_ASSETS = [
  { asset: 'mb-lint.mjs', target: 'scripts/mb-lint.mjs' },
  { asset: 'mb-doctor.mjs', target: 'scripts/mb-doctor.mjs' },
];

const ARGS = new Set(process.argv.slice(2));
const SYNC_MODE = ARGS.has('--sync') || ARGS.has('--force');
const AGENTS_POLICY = process.env.DEVRAILS_AGENTS_POLICY || 'keep';
const TODAY = new Date().toISOString().slice(0, 10);
const GENERATED_MARKER = '<!-- Generated by DevRails 26 init-mb.js. Safe to overwrite with init-mb.js --sync. -->';
const LEGACY_GENERATED_MARKER = '<!-- Generated by memobank init-mb.js. Safe to overwrite with init-mb.js --sync. -->';
const RUNTIME_SKILL_GENERATED_MARKER = '<!-- Generated by DevRails 26 install-framework.mjs. Safe to overwrite with install-framework.mjs --sync. -->';
const INSTALLED_SKILLS_BEGIN_MARKER = '<!-- BEGIN DEVRAILS INSTALLED SKILLS -->';
const INSTALLED_SKILLS_END_MARKER = '<!-- END DEVRAILS INSTALLED SKILLS -->';
const AGENTS_MERGE_WARNING =
  'Крайне рекомендуется проверить обновленный AGENTS.md на противоречия и двусмысленность! Слияние было сделано автоматически, без семантических проверок';
let agentsMerged = false;
const WRITE_RESULTS = [];
const WRITE_BOUNDARY_PATH_PATTERN =
  '^(?!/)(?![A-Za-z]:)(?!.*//)(?!\\.{1,2}(?:/|$))(?!.*\\/\\.{1,2}(?:/|$))(?!.*[\\\\*?\\u0000-\\u001F\\u007F])(?!\\s)(?!.*\\/\\s)(?!.*\\s(?:/|$))[^/]+(?:/[^/]+)*/?$';
const WRITE_BOUNDARY_PATH_SCHEMA = {
  type: 'string',
  minLength: 1,
  pattern: WRITE_BOUNDARY_PATH_PATTERN,
};

const TASK_SCHEMA = {
  $schema: 'https://json-schema.org/draft/2020-12/schema',
  title: 'Memory Bank Task Record',
  type: 'object',
  additionalProperties: false,
  required: [
    'id',
    'title',
    'status',
    'wave',
    'feature',
    'reqs',
    'depends_on',
    'touched_files',
    'tier',
    'gates',
    'verify',
    'docs',
    'evidence_required',
    'source_artifacts',
    'normative_inputs',
    'constraints',
    'invariants',
    'verification_targets',
  ],
  properties: {
    id: { type: 'string', pattern: '^TASK-[0-9]{3}-T[0-3]-FT-[0-9]{3}-W[0-9]+$' },
    title: { type: 'string' },
    status: {
      type: 'string',
      enum: ['planned', 'ready', 'in_progress', 'blocked', 'done', 'failed'],
    },
    wave: { type: 'string' },
    feature: { type: 'string' },
    reqs: { type: 'array', items: { type: 'string' } },
    depends_on: { type: 'array', items: { type: 'string' } },
    touched_files: {
      type: 'array',
      description: 'Advisory, expected, non-exhaustive change surface confirmed by executor preflight.',
      items: { type: 'string' },
    },
    tier: { type: 'string', enum: ['T0', 'T1', 'T2', 'T3'] },
    gates: {
      type: 'array',
      items: {
        type: 'object',
        required: ['name', 'command', 'required'],
        properties: {
          name: { type: 'string' },
          command: { type: 'string' },
          required: { type: 'boolean' },
        },
      },
    },
    verify: {
      type: 'array',
      items: {
        anyOf: [
          { type: 'string' },
          { type: 'object', additionalProperties: true },
        ],
      },
    },
    docs: { type: 'array', items: { type: 'string' } },
    evidence_required: { type: 'array', items: { type: 'string' } },
    purpose: { type: 'string' },
    success_outcome: { type: 'string' },
    anti_goals: { type: 'array', items: { type: 'string' } },
    runtime_context: {
      type: 'object',
      additionalProperties: false,
      properties: {
        write_boundary: {
          type: 'array',
          description: 'Optional hard boundary of literal project-root-relative POSIX paths; omit unless evidence justifies one.',
          items: WRITE_BOUNDARY_PATH_SCHEMA,
        },
        allowed_write_scope: {
          type: 'array',
          description: 'Deprecated alias for write_boundary; do not emit in new task cards.',
          items: WRITE_BOUNDARY_PATH_SCHEMA,
        },
        forbidden_scope: {
          type: 'array',
          description: 'Hard paths or areas that execution must not change.',
          items: { type: 'string' },
        },
        stop_conditions: {
          type: 'array',
          description: 'Hard conditions that require execution to stop and hand off.',
          items: { type: 'string' },
        },
      },
      not: { required: ['write_boundary', 'allowed_write_scope'] },
    },
    source_artifacts: { type: 'array', items: { type: 'string' } },
    normative_inputs: { type: 'array', items: { type: 'string' } },
    constraints: { type: 'array', items: { type: 'string' } },
    invariants: { type: 'array', items: { type: 'string' } },
    verification_targets: { type: 'array', items: { type: 'string' } },
  },
};

const TASK_INDEX = {
  version: 1,
  tasks: [],
};

if (ARGS.has('--help') || ARGS.has('-h')) {
  console.log(`
init-mb.js — initialize Memory Bank skeleton

Usage:
  node init-mb.js                # safe (no overwrites)
  node init-mb.js --sync         # update framework-owned Memory Bank assets/runtime scripts
  node init-mb.js --force        # same behavior as --sync
`.trim());
  process.exit(0);
}

if (SYNC_MODE) {
  console.log('\n[Mode] SYNC: updating framework-owned Memory Bank assets/runtime scripts; project and mixed artifacts are left unchanged.');
}

function ensureDir(rel) {
  const p = path.join(ROOT, rel);
  if (!fs.existsSync(p)) {
    fs.mkdirSync(p, { recursive: true });
    console.log(`  + ${rel}/`);
  }
}

function recordWriteResult(action, rel, ownership) {
  WRITE_RESULTS.push({ action, rel, ownership });

  const symbol = {
    created: '+',
    updated: '~',
    unchanged: '=',
    kept: '!',
  }[action] || '?';
  const detail = {
    updated: 'updated',
    unchanged: 'unchanged',
    kept: 'kept',
  }[action];
  console.log(`  ${symbol} ${rel}${detail ? ` (${detail})` : ''}`);
  return action;
}

function writeFile(rel, content, { overwrite = false, ownership = 'project/mixed' } = {}) {
  const p = path.join(ROOT, rel);
  const existed = fs.existsSync(p);
  let current = null;
  if (existed && !overwrite) {
    if (rel === 'AGENTS.md') {
      current = fs.readFileSync(p, 'utf8');
      if (AGENTS_POLICY === 'replace') {
        overwrite = true;
        ownership = 'framework-owned';
      } else if (AGENTS_POLICY === 'merge') {
        content = mergeAgentsGuide(current, content);
        overwrite = true;
        ownership = 'project/mixed';
        agentsMerged = true;
      } else if (SYNC_MODE && isGeneratedAgentsGuide(current)) {
        overwrite = true;
        ownership = 'framework-owned';
      } else {
        ownership = 'project/mixed';
        return recordWriteResult('kept', rel, ownership);
      }
    } else {
      return recordWriteResult('kept', rel, ownership);
    }
  }

  if (existed) {
    current ??= fs.readFileSync(p, 'utf8');
    if (current === content) {
      return recordWriteResult('unchanged', rel, ownership);
    }
  }

  fs.writeFileSync(p, content, 'utf8');
  return recordWriteResult(existed ? 'updated' : 'created', rel, ownership);
}

function runtimeSkillNames(runtimeRoot) {
  const absRoot = path.join(ROOT, runtimeRoot, 'skills');
  if (!fs.existsSync(absRoot)) return [];

  return fs.readdirSync(absRoot, { withFileTypes: true })
    .map((entry) => entry.name)
    .filter((name) => {
      try {
        return fs.statSync(path.join(absRoot, name, 'SKILL.md')).isFile();
      } catch {
        return false;
      }
    })
    .sort();
}

function markdownCodeCell(value) {
  const escaped = String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/\|/g, '&#124;')
    .replace(/\r/g, '&#13;')
    .replace(/\n/g, '&#10;');
  return `<code>${escaped}</code>`;
}

function installedSkillsBlock() {
  const agents = new Set(runtimeSkillNames('.agents'));
  const claude = new Set(runtimeSkillNames('.claude'));
  const names = [...new Set([...agents, ...claude])].sort();
  const lines = [INSTALLED_SKILLS_BEGIN_MARKER, ''];

  if (names.length === 0) {
    lines.push('_No runtime skills detected in `.agents/skills` or `.claude/skills`._');
  } else {
    lines.push(
      '| Skill | Codex `.agents` | Claude `.claude` |',
      '| --- | --- | --- |',
      ...names.map((name) => (
        `| ${markdownCodeCell(name)} | ${agents.has(name) ? 'yes' : 'no'} | ${claude.has(name) ? 'yes' : 'no'} |`
      )),
    );
  }

  lines.push('', 'Используй guidance ниже только для skill, отмеченного как `yes` в активной runtime surface.', '');
  lines.push(INSTALLED_SKILLS_END_MARKER);
  return lines.join('\n');
}

function skillsIndexContent() {
  return `---
description: Реестр доступных скиллов (когда применять) в этом репозитории.
status: active
---
# Skills

## Installed
${installedSkillsBlock()}

## Guidance for installed skills
- Bootstrap skeleton: mb-init
- Scenario routing: cold-start
- Discovery artifacts: /brainstorm for raw ideas, then /brief; clear concepts may start at /brief
- Project principles: /constitution after /brief or existing PRD context, before /write-prd only when project_principles is not ratified|partial
- PRD → MB: /write-prd, lightweight /spec-init, /prd-to-features, /spec-design, /foundation-to-tasks when required, close the FT-000 foundation gate, then /feature-to-tasks
- SDD design: /spec-init for lightweight route-map preflight, /spec-design for mandatory adaptive global backbone and foundation decision after /prd-to-features, foundation tasking inside /foundation-to-tasks, foundation gate closure before product tasking, initial and repair feature-level design/task reconciliation inside /feature-to-tasks, /spec-auto for autonomous design
- Delegated context routing: /context-manifest when broad discovery is more expensive than direct reads
- Map codebase: /map-codebase
- Execution: /exe
- Verification (UAT): /verify
- Semantic adversarial verification: /red-verify
- Autonomous run: autonomous / autopilot
- Readiness doctor: mb-doctor
- Review: /review-feat-plan, /review-tasks-plan
- Maintenance: mb-garden
`;
}

function installedSection(content) {
  const headings = [...content.matchAll(/^## Installed\r?$/gm)];
  if (headings.length !== 1) return null;

  const heading = headings[0];
  const headingEnd = heading.index + heading[0].length;
  const lineEnd = content.indexOf('\n', headingEnd);
  const bodyStart = lineEnd === -1 ? content.length : lineEnd + 1;
  const nextHeadingPattern = /^## .+\r?$/gm;
  nextHeadingPattern.lastIndex = bodyStart;
  const nextHeading = nextHeadingPattern.exec(content);
  const bodyEnd = nextHeading ? nextHeading.index : content.length;

  return {
    body: content.slice(bodyStart, bodyEnd),
    bodyStart,
    bodyEnd,
  };
}

function isManagedInstalledBody(body) {
  const normalized = body.replace(/\r\n/g, '\n').trim();
  const beginCount = normalized.split(INSTALLED_SKILLS_BEGIN_MARKER).length - 1;
  const endCount = normalized.split(INSTALLED_SKILLS_END_MARKER).length - 1;
  return beginCount === 1
    && endCount === 1
    && normalized.startsWith(`${INSTALLED_SKILLS_BEGIN_MARKER}\n`)
    && normalized.endsWith(`\n${INSTALLED_SKILLS_END_MARKER}`);
}

function writeSkillsIndex() {
  const rel = `${MB}/skills/index.md`;
  const absPath = path.join(ROOT, rel);

  if (!SYNC_MODE || !fs.existsSync(absPath)) {
    return writeFile(rel, skillsIndexContent());
  }

  const current = fs.readFileSync(absPath, 'utf8');
  const section = installedSection(current);
  const normalizedLegacyBody = section?.body.replace(/\r\n/g, '\n');
  const beginMarkerCount = current.split(INSTALLED_SKILLS_BEGIN_MARKER).length - 1;
  const endMarkerCount = current.split(INSTALLED_SKILLS_END_MARKER).length - 1;
  const hasManagedInstalledBlock = beginMarkerCount === 1
    && endMarkerCount === 1
    && section
    && isManagedInstalledBody(section.body);
  const isExactLegacyBaseline = beginMarkerCount === 0
    && endMarkerCount === 0
    && normalizedLegacyBody === '- cold-start\n\n';

  if (!hasManagedInstalledBlock && !isExactLegacyBaseline) {
    console.log(`  ! ${rel}: Installed inventory is unmarked or ambiguous; left unchanged. Reconcile it manually or with /mb-garden when installed.`);
    return recordWriteResult('kept', rel, 'project/mixed');
  }

  const eol = current.includes('\r\n') ? '\r\n' : '\n';
  const nextBlock = installedSkillsBlock().replace(/\n/g, eol);
  const next = `${current.slice(0, section.bodyStart)}${nextBlock}${eol}${eol}${current.slice(section.bodyEnd)}`;
  if (next === current) {
    return recordWriteResult('unchanged', rel, 'framework-owned block');
  }

  fs.writeFileSync(absPath, next, 'utf8');
  return recordWriteResult('updated', rel, 'framework-owned block');
}

function printWriteSummary() {
  if (!SYNC_MODE) return;

  const order = ['created', 'updated', 'unchanged', 'kept'];
  const grouped = new Map();
  WRITE_RESULTS.forEach(({ action, rel, ownership }) => {
    const key = `${action}\u0000${ownership}`;
    if (!grouped.has(key)) grouped.set(key, []);
    grouped.get(key).push(rel);
  });

  console.log('\n[Sync report]');
  order.forEach((action) => {
    [...grouped.entries()]
      .filter(([key]) => key.startsWith(`${action}\u0000`))
      .sort(([left], [right]) => left.localeCompare(right))
      .forEach(([key, paths]) => {
        const ownership = key.split('\u0000')[1];
        console.log(`  ${action} ${ownership} (${paths.length}): ${paths.join(', ')}`);
      });
  });
}

function readUtf8(absPath) {
  return fs.readFileSync(absPath, 'utf8');
}

function resolveReferenceFile(category, filename) {
  const nestedPath = path.join(REFERENCES_DIR, category, filename);
  if (fs.existsSync(nestedPath)) return nestedPath;

  const flattenedPath = path.join(REFERENCES_DIR, `shared-${category}-${filename}`);
  if (fs.existsSync(flattenedPath)) return flattenedPath;

  return null;
}

function listReferenceFilenames(category) {
  const filenames = new Set();
  const nestedDir = path.join(REFERENCES_DIR, category);

  if (fs.existsSync(nestedDir)) {
    fs.readdirSync(nestedDir, { withFileTypes: true })
      .filter((entry) => entry.isFile() && entry.name.toLowerCase().endsWith('.md'))
      .forEach((entry) => filenames.add(entry.name));
  }

  const flattenedPrefix = `shared-${category}-`;
  fs.readdirSync(REFERENCES_DIR, { withFileTypes: true })
    .filter((entry) => (
      entry.isFile()
      && entry.name.startsWith(flattenedPrefix)
      && entry.name.toLowerCase().endsWith('.md')
    ))
    .forEach((entry) => filenames.add(entry.name.slice(flattenedPrefix.length)));

  return [...filenames].sort((left, right) => left.localeCompare(right));
}

function resolveTopLevelReferenceFile(filename) {
  const directPath = path.join(REFERENCES_DIR, filename);
  if (fs.existsSync(directPath)) return directPath;

  const flattenedPath = path.join(REFERENCES_DIR, `shared-${filename}`);
  if (fs.existsSync(flattenedPath)) return flattenedPath;

  return null;
}

function constitutionSkeleton() {
  const absPath = resolveTopLevelReferenceFile(CONSTITUTION_TEMPLATE_FILE);
  if (!absPath) {
    console.error(`\nERROR: Constitution template not found: ${path.join(REFERENCES_DIR, CONSTITUTION_TEMPLATE_FILE)} or flattened shared-${CONSTITUTION_TEMPLATE_FILE}.`);
    console.error('Run init-mb.js from the DevRails 26 package (do not copy it standalone).');
    process.exit(1);
  }

  return readUtf8(absPath).replace(/\{\{TODAY\}\}/g, TODAY);
}

function agentsGuide() {
  const absPath = resolveReferenceFile(AGENTS_TEMPLATE_CATEGORY, AGENTS_TEMPLATE_FILE);
  if (!absPath) {
    console.error(`\nERROR: Deployable AGENTS.md not found: ${path.join(REFERENCES_DIR, AGENTS_TEMPLATE_CATEGORY, AGENTS_TEMPLATE_FILE)} or flattened shared-${AGENTS_TEMPLATE_CATEGORY}-${AGENTS_TEMPLATE_FILE}.`);
    console.error('Run init-mb.js from the DevRails 26 package (do not copy it standalone).');
    process.exit(1);
  }

  return readUtf8(absPath);
}

function resolveRuntimeAsset(filename) {
  const candidates = [
    // Source layout: skills/_shared/scripts/init-mb.js -> skills/mb-garden/assets
    // Prepared installer layout: skills/mb-init/scripts/shared-init-mb.js -> sibling mb-garden/assets
    path.join(SHARED_DIR, '..', 'mb-garden', 'assets', filename),
    path.join(SHARED_DIR, 'assets', filename),
  ];

  return candidates.find((candidate) => fs.existsSync(candidate)) || null;
}

function copyRuntimeScript(asset, target) {
  const absPath = resolveRuntimeAsset(asset);
  if (!absPath) {
    console.error(`\nERROR: Runtime script asset not found: ${asset}`);
    console.error('Run init-mb.js from the DevRails 26 package with mb-garden installed alongside mb-init.');
    process.exit(1);
  }

  writeFile(target, readUtf8(absPath), {
    overwrite: SYNC_MODE,
    ownership: 'framework-owned',
  });
}

function copyRuntimeScripts() {
  RUNTIME_SCRIPT_ASSETS.forEach(({ asset, target }) => copyRuntimeScript(asset, target));
}

function copyWorkflowReference(filename) {
  const absPath = resolveReferenceFile('workflows', filename);
  if (!absPath) {
    console.error(`\nERROR: Workflow reference not found: ${path.join(WORKFLOW_REFERENCES_DIR, filename)} or flattened shared-workflows-${filename}.`);
    console.error('Run init-mb.js from the DevRails 26 package (do not copy it standalone).');
    process.exit(1);
  }

  writeFile(`${MB}/workflows/${filename}`, readUtf8(absPath), {
    overwrite: SYNC_MODE,
    ownership: 'framework-owned',
  });
}

function copyRoleReference(filename) {
  const absPath = resolveReferenceFile('roles', filename);
  if (!absPath) {
    console.error(`\nERROR: Role reference not found: ${path.join(ROLE_REFERENCES_DIR, filename)} or flattened shared-roles-${filename}.`);
    console.error('Run init-mb.js from the DevRails 26 package (do not copy it standalone).');
    process.exit(1);
  }

  writeFile(`${MB}/roles/${filename}`, addGeneratedMarker(readUtf8(absPath)), {
    overwrite: SYNC_MODE,
    ownership: 'framework-owned',
  });
}

function copyProtocolReferences() {
  const filenames = listReferenceFilenames('protocols');
  if (filenames.length === 0) {
    console.error(`\nERROR: No protocol references found in ${path.join(REFERENCES_DIR, 'protocols')} or flattened shared-protocols-*.md files.`);
    console.error('Run init-mb.js from the DevRails 26 package (do not copy it standalone).');
    process.exit(1);
  }

  filenames.forEach((filename) => {
    const absPath = resolveReferenceFile('protocols', filename);
    if (!absPath) {
      console.error(`\nERROR: Protocol reference not found: ${filename}`);
      process.exit(1);
    }

    writeFile(`${MB}/templates/protocols/${filename}`, readUtf8(absPath), {
      overwrite: SYNC_MODE,
      ownership: 'framework-owned',
    });
  });
}

function addGeneratedMarker(markdown) {
  if (markdown.includes(GENERATED_MARKER)) return markdown;

  const frontmatter = markdown.match(/^(---\r?\n[\s\S]*?\r?\n---\r?\n?)/);
  if (frontmatter) {
    return `${frontmatter[1]}${GENERATED_MARKER}\n${markdown.slice(frontmatter[1].length)}`;
  }

  return `${GENERATED_MARKER}\n${markdown}`;
}

function hasGeneratedMarker(content) {
  return content.includes(GENERATED_MARKER)
    || content.includes(LEGACY_GENERATED_MARKER)
    || content.includes(RUNTIME_SKILL_GENERATED_MARKER);
}

function uniqueExistingAgentsContent(existingContent, generatedContent) {
  const generatedLines = new Set(
    generatedContent
      .replace(/\r\n/g, '\n')
      .split('\n')
      .map((line) => line.trimEnd())
  );
  const uniqueLines = [];
  let previousBlank = true;

  existingContent
    .replace(/\r\n/g, '\n')
    .split('\n')
    .forEach((line) => {
      const normalized = line.trimEnd();
      if (normalized === '') {
        if (!previousBlank && uniqueLines.length) {
          uniqueLines.push('');
          previousBlank = true;
        }
        return;
      }
      if (generatedLines.has(normalized)) return;

      uniqueLines.push(normalized);
      previousBlank = false;
    });

  while (uniqueLines[uniqueLines.length - 1] === '') uniqueLines.pop();
  return uniqueLines.join('\n');
}

function mergeAgentsGuide(existingContent, generatedContent) {
  const uniqueExistingContent = uniqueExistingAgentsContent(existingContent, generatedContent);
  if (!uniqueExistingContent.trim()) return `${generatedContent.trimEnd()}\n`;

  return `${generatedContent.trimEnd()}

---

## Preserved Previous AGENTS.md

The following content existed before DevRails 26 bootstrap and was appended automatically.
Review it for contradictions with the generated guide above.

${uniqueExistingContent}
`;
}

function isGeneratedAgentsGuide(content) {
  const normalized = content.replace(/\r\n/g, '\n');
  return hasGeneratedMarker(normalized) || (
    normalized.startsWith('# Agent Operating Guide (Project Map)\n') &&
    normalized.includes('## Runtime vs durable memory') &&
    normalized.includes('## Entry points')
  );
}

function symlinkOrCopy(target, linkName) {
  const linkPath = path.join(ROOT, linkName);
  if (fs.existsSync(linkPath)) return;

  try {
    fs.symlinkSync(target, linkPath);
    console.log(`  ~ ${linkName} -> ${target}`);
  } catch (e) {
    // Windows / restricted env fallback
    const targetPath = path.join(ROOT, target);
    if (fs.existsSync(targetPath)) {
      fs.writeFileSync(linkPath, fs.readFileSync(targetPath, 'utf8'));
      console.log(`  + ${linkName} (copy, symlink failed)`);
    } else {
      console.log(`  ! Could not create ${linkName}: missing target ${target}`);
    }
  }
}

console.log('\n[1/5] Creating directories...');
[
  MB,
  `${MB}/mbb`,
  `${MB}/architecture`,
  `${MB}/guides`,
  `${MB}/adrs`,
  `${MB}/domains`,
  `${MB}/contracts`,
  `${MB}/states`,
  `${MB}/runbooks`,
  `${MB}/workflows`,
  `${MB}/roles`,
  `${MB}/quality`,
  `${MB}/testing`,
  `${MB}/skills`,
  `${MB}/epics`,
  `${MB}/features`,
  `${MB}/behavior-specs`,
  `${MB}/templates/protocols`,
  `${MB}/schemas`,
  `${MB}/tasks`,
  `${MB}/tasks/plans`,
  `${MB}/agents`,
  `${MB}/archive`,
  `${MB}/bugs`,
  'scripts',
  '.tasks',
  '.protocols',
].forEach(ensureDir);

console.log('\n[2/5] Writing core files...');

writeFile('AGENTS.md', agentsGuide(), { ownership: 'framework-owned' });

writeFile(`${MB}/index.md`, `---
description: Главная карта знаний проекта (table of contents) для агентов.
status: active
---
# Memory Bank Index

## Навигация

- [.memory-bank/constitution.md](constitution.md): Project Constitution — top governing policy for agents.
- [.memory-bank/mbb/index.md](mbb/index.md): Правила ведения Memory Bank (MBB).
- [.memory-bank/roles/orchestrator.md](roles/orchestrator.md): Orchestrator role contract.
- [.memory-bank/roles/general.md](roles/general.md): General role contract for one-agent execution.
- [.memory-bank/roles/architect.md](roles/architect.md): Architect role contract.
- [.memory-bank/roles/explorer.md](roles/explorer.md): Explorer role contract.
- [.memory-bank/roles/implementer.md](roles/implementer.md): Implementer role contract.
- [.memory-bank/roles/reviewer.md](roles/reviewer.md): Reviewer role contract.
- [.memory-bank/product.md](product.md): Продукт (C4 L1).
- [.memory-bank/requirements.md](requirements.md): Требования + RTM.
- [.memory-bank/epics/](epics/): Эпики (C4 L2).
- [.memory-bank/features/](features/): Фичи (C4 L3).
- [.memory-bank/behavior-specs/](behavior-specs/): Optional JSON behavior examples linked from feature docs and task \`source_artifacts\`.
- [.memory-bank/tasks/index.json](tasks/index.json): Authoritative JSON task record index.
- [.memory-bank/schemas/task.schema.json](schemas/task.schema.json): JSON schema for task records.
- [.memory-bank/workflows/index.md](workflows/index.md): Workflow router and tier/execution/sync policies.

- [.memory-bank/spec-index.md](spec-index.md): Pure SDD spec registry and planned-spec index.
- [.memory-bank/spec-backbone.md](spec-backbone.md): Pre-PRD framing status and global backbone state for \`/prd-to-features\` and \`/spec-design\`.
- \`.memory-bank/user-scenarios.md\`: optional user scenarios and architecture implications when created by \`/spec-init\` or \`/spec-design\`.
- [.memory-bank/glossary.md](glossary.md): Общий словарь терминов и доменных значений.
- [.memory-bank/invariants.md](invariants.md): Глобальные MUST/NEVER правила.
- [.memory-bank/architecture/](architecture/): Duo + boundaries (WHAT/WHY).
- [.memory-bank/guides/](guides/): Valid HOW docs для использования, запуска и troubleshooting.
- [.memory-bank/adrs/](adrs/): ADR решения.

- [.memory-bank/domains/](domains/): Subject-based domain models, storage, schemas, migrations, and persistence rules.
- [.memory-bank/contracts/](contracts/): Контракты и boundary specs (prefer when present).
- [.memory-bank/contracts/boundary-map.md](contracts/boundary-map.md): Lightweight responsibility/scope boundary notes for decomposition and task runtime context.
- [.memory-bank/states/](states/): Lifecycle/state rules (prefer when present).
- [.memory-bank/runbooks/](runbooks/): Runbooks и operational procedures.
- [.memory-bank/testing/index.md](testing/index.md): Router for testing documentation.
- [.memory-bank/skills/index.md](skills/index.md): Skill registry.
`);

writeFile(`${MB}/mbb/index.md`, `---
description: Memory Bank Bible — правила, инварианты и стандарты документации.
status: active
---
# Memory Bank Bible (MBB)

## Constitution precedence
- [.memory-bank/constitution.md](../constitution.md) is the top governing policy for agent decisions.
- MBB, spec-index, spec-backbone, invariants, contracts, states, testing, and workflow docs refine the Constitution and MUST NOT contradict it.

## SSOT pyramid
- **Code**: WHAT/HOW — implementation truth.
- **Docstrings**: contracts + @docs pointers.
- **Memory Bank**: WHY/WHERE — boundaries, invariants, navigation.

## Hard rules
1. Every \`.memory-bank/**/*.md\` MUST have frontmatter with \`description:\`.
2. If a folder has >3 docs, add an \`index.md\` router.
3. Use annotated links: \`[.memory-bank/path](rel-path): короткое описание\`.
4. Atomic docs: one cohesive concern per doc; split by boundary, change cadence,
   consumers, or reuse, not by file length alone.
5. Duo docs remain valid: \`architecture/\` (WHAT/WHY) + \`guides/\` (HOW), cross-link both ways for concepts that use the classic pair model.
6. C4 layering: L1 product → L2 epics → L3 features → L4 plans/tasks.
7. Docs First: update MB immediately after finishing a task.
8. Refactor MB every 5–10 updates (split, merge, archive).
9. Separate facts from interpretations: mark hypotheses explicitly ("предположительно", "требует проверки").
10. After merge/rebase conflicts: re-check MB consistency.
11. MB-SYNC after each wave/significant change (see \`workflows/mb-sync.md\`).
12. When present, \`constitution.md\`, \`spec-backbone.md\`, \`spec-index.md\`, \`glossary.md\`, \`invariants.md\`, \`contracts/*\`, \`states/*\`, \`runbooks/*\`, and \`testing/*\` act as an explicit normative layer and should be linked from relevant docs.
13. Features compose product behavior and exact canonical spec links. New design
    specs use subject-based paths without \`FT-<NNN>\` names or feature ownership.

## Forbidden
- Copy-paste implementation details / pseudocode
- Duplicating configs instead of linking to source
- Speculative claims without evidence from code/metrics/tests

## Allowed / encouraged
- Invariants (MUST/NEVER)
- Contracts at boundaries
- Decision rationale + pointers
- Runbooks and verification procedures
`);

writeFile(`${MB}/spec-index.md`, `---
description: Pure SDD spec registry and planned-spec index.
status: active
last_updated: ${TODAY}
source_of_truth:
  - .memory-bank/spec-index.md
---
# SDD Spec Index

## Purpose
- Keep a concise registry of existing and planned SDD specs.
- Read this index before creating new specs or doing serious design-pressure work.
- Keep readiness, open design questions, backbone status, and routing handoffs in [.memory-bank/spec-backbone.md](spec-backbone.md).
- Feature \`spec_design_status\` lives in feature frontmatter, not in this index.

## Spec Registry
| Type | Path | Status | Scope | Change route |
|---|---|---|---|---|
| governance | [.memory-bank/constitution.md](constitution.md) | active | Top governing policy. | /constitution |
| invariants | [.memory-bank/invariants.md](invariants.md) | planned | Global MUST/NEVER rules when evidence exists. | /spec-init or /spec-design |
| glossary | [.memory-bank/glossary.md](glossary.md) | planned | Shared vocabulary. | /brief, /spec-init, or /spec-design |
| contract | [.memory-bank/contracts/boundary-map.md](contracts/boundary-map.md) | draft | Lightweight responsibility/scope notes for task boundaries. | /spec-init or /spec-design |
${TESTING_SPEC_REGISTRY_ROW}

## Planned Specs
| Area | Expected path | Needed by | Notes |
|---|---|---|---|
| user_scenarios | .memory-bank/user-scenarios.md | /prd-to-features, /spec-design | Create only when scenario evidence exists or gaps must be explicit. |
| core_domain | .memory-bank/domains/core-domain.md | /prd-to-features, /spec-design | Create only when domain model affects decomposition or shared design. |
| boundary_hints | .memory-bank/contracts/boundary-map.md | /prd-to-features, /spec-design | Seeded lightweight template; fill only evidence-backed responsibility/scope notes, no endpoint/OpenAPI details. |
| lifecycle_hints | .memory-bank/states/lifecycle-map.md | /prd-to-features, /spec-design | Create only when lifecycles affect feature boundaries. |
| system_architecture | .memory-bank/architecture/system-architecture.md | /spec-design | Candidate architecture hub; fill only when selected or needed by /spec-design. |
| interface_contract_specs | .memory-bank/contracts/*, .memory-bank/testing/*, and .memory-bank/runbooks/* | /spec-design, /foundation-to-tasks, /feature-to-tasks | Generate/update Interface Specification and only applicable Component/API/Event/Data contracts, protocol/agent/tool I/O, boundary compatibility, evidence/redaction, safety/security, testing, runbook, or verification contracts. Data Contract defines payloads crossing a boundary. |
| data_specs | .memory-bank/domains/* and .memory-bank/states/* | /spec-design, /feature-to-tasks | Generate/update Data Specification for internal models, DB schemas, storage/persistence/migrations, internal data formats, validation/serialization rules, lifecycle, retention, seed, or runtime data paths. |
| foundation_substrate_specs | .memory-bank/architecture/*, .memory-bank/contracts/*, .memory-bank/domains/*, .memory-bank/states/*, .memory-bank/testing/*, .memory-bank/runbooks/* | /foundation-to-tasks | Apply Architecture, Interfaces/Contracts, and Data lenses to the walking-skeleton proof path. Generate only applicable subject-based substrate contracts/specs. Product-level detail reuses or extends those paths later. |
| subject_feature_concerns | .memory-bank/contracts/*, .memory-bank/domains/*, .memory-bank/states/*, .memory-bank/testing/*, .memory-bank/runbooks/*, or .memory-bank/guides/* | /feature-to-tasks | Discover existing canonical specs first; create only missing subject-based concerns and link exact paths from features/tasks. |

## Broken / Missing Links
- TBD

## Update Rules
- Keep this file as index/registry only: types, canonical paths, statuses,
  scopes, change routes, and broken links.
- Canonical identity is the path. Do not add a separate spec key, feature owner,
  \`used_by\`, or reverse-usage copy; derive usage from feature/task links.
- Do not add global backbone status, backbone matrices, feature status maps, long hard rules, or open design question dumps here.
- Use [.memory-bank/spec-backbone.md](spec-backbone.md) for pre-PRD readiness, decomposition inputs, global backbone status, matrix, and handoffs.
- Use linked specs or ADRs for detailed decisions, rationale, contracts, state transitions, schemas, invariants, and testing rules.
`);

writeFile(`${MB}/spec-backbone.md`, `---
description: Pre-PRD spec framing and global SDD backbone state.
status: active
---
# SDD Spec Backbone

## Pre-PRD Spec Status
- Status: blocked
- Last updated: ${TODAY}
- Notes: Run /spec-init after /write-prd to determine whether PRD decomposition is safe.

## Decomposition Inputs
- User scenarios: not_started
- Domain model: not_started
- Constraints: not_started
- Non-goals: not_started
- Risks: not_started
- Boundary hints: not_started
- Lifecycle hints: not_started

## Open Design Questions
- TBD

## Backbone Area Matrix
| Area | Status | Authoritative source | Notes |
|---|---|---|---|
| architecture_style | blocked | - | Decide in /spec-design after /prd-to-features. |
| source_of_truth | blocked | - | Decide in /spec-design after /prd-to-features. |
| module_boundaries | blocked | .memory-bank/contracts/boundary-map.md | Fill only evidence-backed responsibility/scope notes; decide in /spec-design after /prd-to-features. |
| user_scenarios | blocked | .memory-bank/user-scenarios.md | Create/review when scenarios affect decomposition or architecture. |
| constraints | blocked | - | Capture in /spec-init and refine in /spec-design. |
| non_goals | blocked | - | Capture in /spec-init and refine in /spec-design. |
| domain_model | blocked | .memory-bank/domains/core-domain.md | Create only when domain model affects decomposition or shared design. |
| data_flow | blocked | - | Decide in /spec-design after /prd-to-features. |
| storage | blocked | - | Decide in /spec-design after /prd-to-features. |
| api_contracts | blocked | - | Decide authoritative/needed/not_applicable/blocked in /spec-design. |
| event_message_contracts | blocked | - | Decide authoritative/needed/not_applicable/blocked in /spec-design. |
| agent_io_contracts | blocked | - | Decide authoritative/needed/not_applicable/blocked in /spec-design. |
| security_safety | blocked | - | Decide in /spec-design after /prd-to-features. |
| deployment | blocked | - | Decide in /spec-design after /prd-to-features. |
| risks | blocked | - | Capture in /spec-init and refine in /spec-design. |
| open_questions | blocked | - | Resolve or keep blocked. |

## Handoff To /prd-to-features
- Ready: no
- Required reads: .memory-bank/prd.md, .memory-bank/spec-index.md, this file, and linked pre-PRD specs.
- Stop conditions: Pre-PRD Spec Status is missing, stale, or blocked.

## Handoff To /spec-design
- Global Backbone Status: intentionally pending until /spec-design
- Downstream readiness: /feature-to-tasks, /autopilot, and autonomous scheduler mode must wait for /spec-design.
- Backbone areas to revisit: all
- Candidate specs: see .memory-bank/spec-index.md Planned Specs.

## Global Backbone Status
- Status: blocked
- Planning Revision: 0
- Mode: pending
- Architecture artifact strategy: pending
- Not applicable areas:
  - TBD
- Notes: /spec-design has not completed the global architecture scaffold yet.
`);

writeFile(`${MB}/constitution.md`, constitutionSkeleton());

writeFile(`${MB}/glossary.md`, `---
description: Словарь терминов, сущностей и agreed vocabulary проекта.
status: draft
---
# Glossary

## Terms
- Term: definition

## Notes
- Используй этот файл для устранения неоднозначностей в названиях и статусах.
`);

writeFile(`${MB}/invariants.md`, `---
description: Глобальные инварианты и запреты проекта (MUST/NEVER).
status: draft
---
# Invariants

## MUST
- TBD

## NEVER
- TBD

## Notes
- Ссылайся на этот файл из архитектурных, контрактных и execution docs, если правило является cross-cutting.
`);

writeFile(`${MB}/architecture/system-architecture.md`, `---
description: Compact system architecture hub and Architecture Spine for serious design-pressure work.
status: draft
---
# System Architecture

## System Goal
- TBD

## Main Constraints
- TBD

## Architecture Spine

Use this section only for durable decisions that constrain shared-boundary, contract, state/data/runtime/security, or strict work. Keep it short; detailed rationale belongs in ADRs or decision logs.

### Architecture Decisions

#### AD-NNN — <short decision>
- Binds:
- Prevents:
- Rule:
- Verification:
- Source:

### Deferred Decisions

| Decision | Deferred because | Revisit when |
|---|---|---|
| TBD | TBD | TBD |

## Main Modules / Bounded Contexts
- TBD

## Data Flow
- TBD

## API / Contract Boundaries
- See [.memory-bank/contracts/boundary-map.md](../contracts/boundary-map.md).
`);

writeFile(`${MB}/contracts/boundary-map.md`, `---
description: Lightweight responsibility and scope boundary notes for decomposition, implementation, and verification.
status: draft
---
# Boundary Map

## Purpose
- Keep lightweight boundary notes that help agents avoid crossing ownership, responsibility, or write-scope lines during decomposition and task execution.
- Use this file as an existing contract/spec input when task records need \`purpose\`, \`success_outcome\`, \`anti_goals\`, \`runtime_context.write_boundary\`, \`runtime_context.forbidden_scope\`, or \`runtime_context.stop_conditions\`.

## Boundary Notes
| Boundary | Purpose | Direction | Owner | Known Constraints | Questions |
|---|---|---|---|---|---|
| TBD | TBD | TBD | TBD | TBD | TBD |

## Boundary: <producer> -> <consumer>

- Owner:
- Consumers:
- Allowed calls:
- Forbidden calls:
- Data owner:
- Compatibility rule:
- Verification:
- Linked ADs:

## Runtime Context Hints
- Write boundary hints: TBD
- Forbidden scope hints: TBD
- Stop condition hints: TBD

## Update Rules
- Keep entries evidence-backed and short.
- Do not add endpoint lists, OpenAPI details, request/response schemas, auth policy, error-code design, or implementation pseudocode here.
- Do not create new task fields for boundaries; link this file through existing task fields such as \`source_artifacts\`, \`normative_inputs\`, \`constraints\`, \`invariants\`, or \`verification_targets\`, and copy executable scope into \`runtime_context\` when needed.
`);

writeFile(`${MB}/product.md`, `---
description: Product brief (C4 L1): что это, для кого, core value, ограничения.
status: draft
---
# Product

## What this is

## Core value

## Audience

## Primary user flow

## Constraints
- Tech stack:
- Timeline:
- Non-goals:
`);

writeFile(`${MB}/requirements.md`, `---
description: Требования (REQ-IDs) + traceability matrix (RTM).
status: draft
---
# Requirements

## Status model
- Document \`status\`: \`draft|active|deprecated|archived\`
- RTM \`Lifecycle\`: \`planned|implemented|verified\`

## REQ list
- (fill from PRD; do not invent requirements without evidence)

## Out of scope
- ...

## Traceability (RTM)
| REQ | Epic | Feature | Test | Lifecycle |
|---|---|---|---|---|
| REQ-XXX | EP-XXX | FT-XXX | test:... | planned |
`);

writeFile(`${MB}/schemas/task.schema.json`, `${JSON.stringify(TASK_SCHEMA, null, 2)}\n`, {
  overwrite: SYNC_MODE,
  ownership: 'framework-owned',
});

writeFile(`${MB}/tasks/index.json`, `${JSON.stringify(TASK_INDEX, null, 2)}\n`);

writeFile(`${MB}/testing/index.md`, `---
description: Router for testing and verification documentation.
status: active
---
# Testing Documentation

${TESTING_STRATEGY_ROUTER_ENTRY}
- [SDD Spec Index](../spec-index.md): authoritative registry предметных testing и verification specs.
`);

if (!MEMORY_BANK_EXISTED_AT_START) {
  writeFile(`${MB}/testing/strategy.md`, `---
description: Minimal framework baseline policy for risk-based testing and verification evidence.
status: active
---
# Testing Strategy

## Risk-based checks
- Choose checks from concrete product and regression risks in the PRD,
  Constitution, requirements, features, subject specs, and actual project shape.
- Use the cheapest check that reliably proves the required behavior.
- Add a broader or more expensive test level only when a narrower check cannot
  prove the outcome.
- Do not create tests merely to fill unit, integration, or e2e categories.

## Integrity
- Do not weaken assertions, disable failing checks, or replace meaningful
  verification with decorative coverage to obtain a green result.
- Treat a failing applicable check as evidence to investigate or resolve within
  explicit scope.

## Evidence and ownership
- T2/T3 tasks require an executable verification path. T0/T1 may use compact
  evidence or a documented no-runnable-check route when no meaningful check exists.
- Store commands, results, logs, screenshots, and verdicts in the task-selected
  \`.protocols/<TASK_ID>/\` and \`.tasks/<TASK_ID>/\` paths, not in this policy.
- Keep product quality requirements in requirements/features, concrete
  verification contracts in subject specs, and executable gates in task records.
`);
}

writeSkillsIndex();

writeFile(`${MB}/workflows/index.md`, `---
description: Router for generated DevRails execution, autonomy, tier, and synchronization workflows.
status: active
---
# Workflow Index

- [.memory-bank/workflows/tier-policy.md](tier-policy.md): Task tier routing, protocol depth, and closure gates.
- [.memory-bank/workflows/execute-loop.md](execute-loop.md): Manual and autonomous task execution sequence.
- [.memory-bank/workflows/autonomy-policy.md](autonomy-policy.md): Unattended-run guardrails, budgets, and terminal states.
- [.memory-bank/workflows/mb-sync.md](mb-sync.md): Durable state synchronization boundaries and checklist.
`);

writeFile(`${MB}/changelog.md`, `---
description: Лог изменений Memory Bank.
status: active
---
# Changelog

## [${TODAY}] Initial setup
- Created Memory Bank skeleton
- Seeded core docs (product, requirements, testing, task registry)
`);

copyWorkflowReference('mb-sync.md');
copyWorkflowReference('tier-policy.md');
copyWorkflowReference('autonomy-policy.md');
copyWorkflowReference('execute-loop.md');
copyRoleReference('orchestrator.md');
copyRoleReference('general.md');
copyRoleReference('architect.md');
copyRoleReference('explorer.md');
copyRoleReference('implementer.md');
copyRoleReference('reviewer.md');
copyProtocolReferences();

writeFile(`${MB}/adrs/ADR-000-template.md`, `---
description: "ADR-000: Шаблон для архитектурных решений."
status: active
owner: architecture
last_updated: ${TODAY}
source_of_truth:
  - .memory-bank/adrs/ADR-000-template.md
---
# ADR-000: Template

## ADR Status
accepted

## Context
Используй этот файл как шаблон для новых ADR.
Копируй и заполняй: Status, Context, Decision, Consequences, Alternatives.

## Decision
Каждое значимое архитектурное решение фиксируется как ADR в этой папке.

## Consequences
Все решения трассируемы и reviewable.
`);

console.log('\n[3/4] Writing runtime scripts and creating symlinks...');
copyRuntimeScripts();
symlinkOrCopy('AGENTS.md', 'CLAUDE.md');
symlinkOrCopy('AGENTS.md', 'GEMINI.md');

console.log('\n[4/4] Finalizing...');
if (agentsMerged) console.log(`\n${AGENTS_MERGE_WARNING}`);
printWriteSummary();

console.log('\n[Done] Memory Bank skeleton initialized.');
console.log(`\nMemory Bank initialized in: ${ROOT}`);
